[all_servers]
Amaze_Prod_App ansible_host=164.52.194.107 ansible_user=app client_name=Amaze_Prod_App pm2_user=app
Amaze_Dev_App ansible_host=164.52.208.158 ansible_user=app client_name=Amaze_Dev_App pm2_user=app
#Amaze_Master_DB ansible_host=164.52.195.146 ansible_user=root client_name=Amaze_master_DB

Evervent_Deployment ansible_host=164.52.215.248 ansible_user=app client_name=Evervent_Deployment pm2_user=app
Evervent_Roweley ansible_host=216.48.180.28 ansible_user=app client_name=Evervent_Rowley pm2_user=app
#Jenkins ansible_host=101.53.157.19 ansible_user=root client_name=Jenkins
KSecure ansible_host=164.52.192.176 ansible_user=app client_name=KSecure pm2_user=app
#N8N ansible_host=164.52.200.189 ansible_user=root client_name=N8N
#Zabbix ansible_host=216.48.184.140 ansible_user=root client_name=Zabbix

India_insure_dev ansible_host=216.48.186.13 ansible_user=app client_name=India_insure_dev pm2_user=app
India_Insure_Prod ansible_host=10.7.128.7 ansible_user=app client_name=India_Insure_Prod pm2_user=app
#India_Insure_Slave ansible_host=10.7.128.9 ansible_user=root client_name=India_Insure_Slave
#India_Insure_Maxscale ansible_host=10.7.128.10 ansible_user=root client_name=India_Insure_Maxscale
#India_Insure_MasterDB ansible_host=10.7.128.8 ansible_user=root client_name=India_Insure_MasterDB

JB_BodaApp_Prod ansible_host=10.6.208.7 ansible_user=app client_name=JB_BodaApp_Prod pm2_user=app
JB_BodaApp_Dev ansible_host=101.53.135.104 ansible_user=app client_name=JB_BodaApp_Dev pm2_user=app
#JB_Boda_MasterDB ansible_host=10.6.208.8 ansible_user=root client_name=JB_Boda_MasterDB

#Muthoot_Master_db ansible_host=34.131.121.31 ansible_user=app client_name=Muthoot_Master_db

Policyparivaar_App_Prod ansible_host=10.6.108.9 ansible_user=app  client_name=Policyparivaar_App_Prod pm2_user=app
Policyparivaar_App_Dev ansible_host=164.52.215.179 ansible_user=app client_name=Policyparivaar_App_Dev pm2_user=app
#Policyparivaar_Master_DB ansible_host=10.6.108.10 ansible_user=root client_name=Policyparivaar_Master_DB
#Policyparivaar_Master_DB ansible_host=10.6.108.10 ansible_user=root ansible_python_interpreter=/usr/bin/python3.10 client_name=Policyparivaar_Master_DB

Rahee_App_Prod ansible_host=10.11.138.7 ansible_user=app client_name=Rahee_App_Prod pm2_user=app
Rahee_App_Dev ansible_host=164.52.201.235 ansible_user=app client_name=Rahee_App_Dev pm2_user=app
#Rahee_Master_DB ansible_host=10.11.138.8 ansible_user=root client_name=Rahee_Master_DB

EB_Savvvyy ansible_host=164.52.194.19 ansible_user=app client_name=EB_Savvvyy pm2_user=app

EB_Savvvyy ansible_host=164.52.194.19 ansible_user=app client_name=EB_Savvvyy pm2_user=app

Sorigin_Development ansible_host=164.52.213.169 ansible_user=app client_name=Sorigin_Development pm2_user=app

#Sorigin_EB ansible_host=164.52.210.147 ansible_user=app client_name=Sorigin_EB pm2_user=app
